### ISSUE TITLE
Error,  execute build.sh

### ISSUE THREAD

**Issue by stallman-cui** [appnexus/pyrobuf#1] opened 2015-12-19 07:37 UTC
I put  ens_sdk.proto to messages, and run ./build.sh, then error
Traceback (most recent call last):
  File "gen_all_messages.py", line 33, in <module>
    gen_all_messages()
  File "gen_all_messages.py", line 21, in gen_all_messages
    msgdef = parser.parse_from_filename(spec)
  File "/Users/david/git_workspace/pyrobuf/parse_proto.py", line 162, in parse_from_filename
    return self.parse(s)
  File "/Users/david/git_workspace/pyrobuf/parse_proto.py", line 140, in parse
    for token in tokens:
  File "/Users/david/git_workspace/pyrobuf/parse_proto.py", line 134, in tokenize
    raise Exception("Unexpected character '%s' in line %d: '%s'" % (s[pos], line, s[pos-10:pos+10]))
Exception: Unexpected character 'm' in line 1: ''

my proto file is 
```
message TestEns {
	optional uint32 ip = 1;
	optional int32 port = 2;
	optional int32 weight = 3;
	optional uint32 key_id = 4;
}
```

**Comment by rileyberton** [comment] 2015-12-19 15:56
I can't reproduce this.. 

```
rberton:pyrobuf rberton$ cat messages/test_ens.proto
message TestEns {
    optional uint32 ip = 1;
    optional int32 port = 2;
    optional int32 weight = 3;
    optional uint32 key_id = 4;
}
rberton:pyrobuf rberton$ python gen_all_messages.py
parsing messages/test_ens.proto
parsing messages/test_message.proto
parsing messages/test_ref_message.proto

rberton:pyrobuf rberton$ cat out/test_ens_proto.pxd
from libc.stdint cimport *
from libc.string cimport *

from pyrobuf_list cimport *
from pyrobuf_util cimport *

import json


cdef class TestEns:

    cdef uint32_t _ip
    cdef int32_t _port
    cdef int32_t _weight
    cdef uint32_t _key_id

    cpdef reset(self)

    cdef int _protobuf_deserialize(self, const unsigned char *memory, int size)

    cdef void _protobuf_serialize(self, bytearray buf)

```

What version of python?

```
rberton:pyrobuf rberton$ python --version
Python 2.7.10
```

**Comment by stallman-cui** [comment] 2015-12-20 10:12
Operation System: mac + os caption
My python version is 
```
~   python --version
Python 2.7.11
```
This just depend python or depend other something, like protoc ?

**Comment by gucluoz** [comment] 2015-12-21 11:29
I guess I got the same thing with Python 3.5.0 :
```
parsing messages/sensor.proto
Traceback (most recent call last):
  File "gen_all_messages.py", line 33, in <module>
    gen_all_messages()
  File "gen_all_messages.py", line 21, in gen_all_messages
    msgdef = parser.parse_from_filename(spec)
  File "/Users/gucluozturk/pyrobuf/parse_proto.py", line 162, in parse_from_filename
    return self.parse(s)
  File "/Users/gucluozturk/pyrobuf/parse_proto.py", line 140, in parse
    for token in tokens:
  File "/Users/gucluozturk/pyrobuf/parse_proto.py", line 134, in tokenize
    raise Exception("Unexpected character '%s' in line %d: '%s'" % (s[pos], line, s[pos-10:pos+10]))
Exception: Unexpected character 'm' in line 1: ''
```
Here is my sensor.proto :
```
message sensor {
  required string m1 = 1;
  required string m2 = 2;
  required string m3 = 3;
  required string m4 = 4;
  required float value = 5; 
}
```

**Comment by gucluoz** [comment] 2015-12-21 11:54
Well, I got mine fixed by capitalising 's' of '**message Sensor {**' since the tokenizer reg ex. expects **[A-Z]** for the first character of message name as follows :
~~~
(?P<MESSAGE>message\s+([A-Z][0-9A-Za-z]*))
~~~

**Comment by gucluoz** [comment] 2015-12-21 12:03
I got mine fixed by capitalising '**s**' of 'message **S**ensor {....}'

**Comment by tburmeister** [comment] 2015-12-22 14:52
Yes, the parser expects the first letter of a message name to be capitalized - this is consistent with the official [style guide](https://developers.google.com/protocol-buffers/docs/style) but is not actually a requirement - I can change this to be more permissive.

**Closed** 2016-03-25 08:53 UTC
